// import localFont from 'next/font/local'
import type { Metadata } from 'next'
import './globals.css'
import StoreProvider from './StoreProvider'

// const bmJua = localFont({
//   src: '../public/fonts/BMJUA_woff2.woff2',
//   display: 'swap',
//   variable: '--font-bmjua',
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang="ko">
        <body className="">{children}</body>
      </html>
    </StoreProvider>
  )
}
