import localFont from 'next/font/local'
import type { Metadata } from 'next'
import './globals.css'

import StoreProvider from './StoreProvider'
import Provider from '@/utils/QueryProviders'
import React from 'react'
import Header from '@/features/header/Header'

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} font-pretendard`}>
        <StoreProvider>
          <Provider>
            <Header />
            <main className="pt-12 lg:h-screen">
              <div className="flex flex-col items-center justify-start space-y-4 text-center break-keep">
                {children}
              </div>
            </main>
          </Provider>
        </StoreProvider>
      </body>
    </html>
  )
}
