import localFont from 'next/font/local'
import type { Metadata } from 'next'
import './globals.css'

import StoreProvider from './StoreProvider'
import Provider from '@/utils/QueryProviders'

const pretendard = localFont({
  src: '../fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang="ko">
        <body className={`${pretendard.variable} font-pretendard`}>
          <Provider>{children}</Provider>
        </body>
      </html>
    </StoreProvider>
  )
}
